<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.611" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2025-09-16T04:44:20" tests="0" file="cypress/e2e/smoke-avi-lab.cy.ts" time="0.000" failures="0">
  </testsuite>
  <testsuite name="AVI_LAB – Toggles and Basic Flow (smoke)" timestamp="2025-09-16T04:44:20" tests="1" time="1.581" failures="2">
    <testcase name="AVI_LAB – Toggles and Basic Flow (smoke) shows Questions tab, lexicon toggles and Basic Info Flow" time="0.189" classname="shows Questions tab, lexicon toggles and Basic Info Flow">
      <failure message="The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  &gt; Cannot set properties of null (setting &apos;innerHTML&apos;)

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application" type="TypeError"><![CDATA[TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot set properties of null (setting 'innerHTML')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
    at AVILabComplete.setupUI (http://localhost:8080/app-complete.js:98:23)
    at AVILabComplete.init (http://localhost:8080/app-complete.js:72:14)]]></failure>
    </testcase>
    <testcase name="AVI_LAB – Toggles and Basic Flow (smoke) &quot;after all&quot; hook: generateReport for &quot;shows Questions tab, lexicon toggles and Basic Info Flow&quot;" time="0.189" classname="&quot;after all&quot; hook: generateReport for &quot;shows Questions tab, lexicon toggles and Basic Info Flow&quot;">
      <failure message="`cy.task(&apos;coverageReport&apos;)` failed with the following error:

&gt; Command failed with exit code 1: npm run coverage:report

https://on.cypress.io/api/task

Because this error occurred during a `after all` hook we are skipping all of the remaining tests.

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail" type="CypressError"><![CDATA[CypressError: `cy.task('coverageReport')` failed with the following error:

> Command failed with exit code 1: npm run coverage:report

https://on.cypress.io/api/task

Because this error occurred during a `after all` hook we are skipping all of the remaining tests.

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:138627:70)
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1777:23)
    at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1489:31)
    at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:1546:18)
    at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:1591:10)
    at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:1667:18)
    at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:2377:12)
    at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:2370:9)
    at Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2386:5)
    at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2256:14)

From Node.js Internals:
  Error: Command failed with exit code 1: npm run coverage:report
      at makeError (/Users/josuehernandez/pwa_angular/node_modules/@cypress/code-coverage/node_modules/execa/lib/error.js:59:11)
      at handlePromise (/Users/josuehernandez/pwa_angular/node_modules/@cypress/code-coverage/node_modules/execa/index.js:114:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)]]></failure>
    </testcase>
  </testsuite>
</testsuites>